version: '3.3'
services:
  MySQLDB: # Service name
    image: mysql:8.0
    container_name: MySQLDB
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    volumes:
      - ./data:/var/lib/mysql
  MariaDB: # Service name
    image: mariadb:10.5
    container_name: MariaDB
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    volumes:
      - ./data:/var/lib/mysql